In [2]:
%matplotlib inline
import numpy as np
import pandas as pd



np.random.seed(29)

1. How likely is it that you roll doubles when rolling two dice?

In [5]:
# Set up for 2 dice w/ 10000 trial for getting doubles
n_dice = 2
n_trials = 10000
dice = [1,2,3,4,5,6]
doubles_rand = np.random.choice(dice,(n_trials, n_dice))

In [6]:
doubles_rand[:10,:]

array([[3, 3],
       [3, 3],
       [2, 1],
       [4, 1],
       [4, 4],
       [6, 4],
       [4, 1],
       [4, 3],
       [4, 6],
       [4, 2]])

In [9]:
# dice1 needs to = dice 2 

/var/folders/mj/fstq2n8s1gs942htzygkxlj40000gn/T/ipykernel_7368/3499864966.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  (doubles_rand[:, 0] == doubles_rand[0,:]).sum(axis=1)


AttributeError: 'bool' object has no attribute 'sum'

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?



In [10]:
outcomes = ['H','T']
n_trials = 8
n_sim = 10_000
eight_flips = np.random.choice(outcomes, (n_sim, n_trials))

In [11]:
eight_flips[:10,:]

array([['H', 'T', 'T', 'H', 'T', 'H', 'H', 'T'],
       ['H', 'T', 'T', 'H', 'T', 'H', 'T', 'H'],
       ['T', 'H', 'H', 'H', 'T', 'H', 'T', 'H'],
       ['T', 'H', 'H', 'H', 'T', 'H', 'T', 'H'],
       ['H', 'T', 'T', 'H', 'T', 'H', 'T', 'T'],
       ['T', 'T', 'H', 'H', 'H', 'T', 'T', 'T'],
       ['T', 'H', 'T', 'H', 'H', 'H', 'H', 'H'],
       ['H', 'H', 'H', 'H', 'H', 'T', 'H', 'T'],
       ['T', 'T', 'T', 'H', 'H', 'T', 'H', 'H'],
       ['H', 'T', 'T', 'H', 'H', 'H', 'H', 'T']], dtype='<U1')

In [15]:
# Prob for exactly 3 Heads
(eight_flips == 'H').sum(axis=1)
((eight_flips == 'H').sum(axis=1) == 3).sum() / n_sim

0.2234

In [16]:
# Prob for more than 3 heads
((eight_flips == 'H').sum(axis=1) > 3).sum() / n_sim

0.6297

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?



In [25]:
# 3 web
# 1 data
# assume that the class sizes are all the same and there will be a 1/3 chance 1 student is data and on 1 billboard
# so use the rand.rand?
da_to_web = (1/3)
billboards = 2
n_simulate = 10000
class_data = np.random.random((n_simulate, billboards))

# 2 bill boards

In [26]:
class_data[:10, :]

array([[0.48614082, 0.59709603],
       [0.61406416, 0.84943868],
       [0.05694802, 0.24438293],
       [0.90710753, 0.64509188],
       [0.48217333, 0.87728867],
       [0.75274143, 0.24131581],
       [0.44621517, 0.10029338],
       [0.53084673, 0.87602044],
       [0.36308207, 0.13954565],
       [0.08671018, 0.61052185]])

In [29]:
# chances 1 billboard would be 1 in 3 chance
one_in_three = (class_data < da_to_web)

In [32]:
# 2 data 2 board
((one_in_three.sum(axis=1)) == 2).mean()

0.1135

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values



In [44]:
poptarts_mean = 3
pt_sd = 1.5
poptart_stock = 17
days = 5
fat_kids = np.random.normal(poptarts_mean, pt_sd, days)


In [46]:
fat_kids
# come back to this

array([1.86035879, 3.00053896, 2.36773578, 3.68093645, 6.86085918])

5. Compare Heights

    * Men have an average height of 178 cm and standard deviation of 8cm.
    * Women have a mean of 170, sd = 6cm.
    * Since you have means and standard deviations, you can use np.random.normal to generate observations.
    * If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?



In [53]:
men_ht_mean = 178
men_sd = 8
women_ht_mean = 170
women_sd = 6

men_dist = np.random.normal(men_ht_mean, men_sd, size=50)

women_dist = np.random.normal(women_ht_mean, women_sd, size=50)

In [50]:
men_dist

array([180.81597496, 171.75156383, 176.51762393, 179.58983121,
       189.88050966, 182.50226001, 170.15114703, 190.34041908,
       180.37416498, 178.44137339, 181.78084501, 179.19034328,
       187.3036615 , 184.41276115, 182.43994334, 181.62837771,
       181.29229722, 186.54572352, 177.27360356, 176.71963992,
       181.77025572, 179.9608001 , 188.04940823, 179.88001965,
       175.43502892, 189.22454629, 178.36888528, 171.88353564,
       176.64560452, 161.70399237, 171.98346201, 182.74300062,
       173.49597361, 190.03699954, 183.6285578 , 189.97655715,
       177.15842225, 180.99741499, 182.74565751, 175.21893336,
       180.13862868, 175.80905423, 194.43703694, 186.04320844,
       157.66847304, 174.64788357, 173.86157795, 188.6668234 ,
       191.74503873, 171.97300717, 162.25462836, 190.56712388,
       166.5353889 , 183.04037715, 178.83559608, 176.59802136,
       177.15349136, 158.69740324, 182.93345587, 181.10597994,
       176.93505981, 174.6442983 , 175.89374606, 188.35

In [54]:
women_dist

array([167.65953554, 174.58185883, 162.84101523, 182.52287809,
       153.68197234, 171.12832106, 163.52922284, 167.22696173,
       168.91367725, 172.50178708, 180.84184319, 170.87639192,
       166.95459196, 172.37013665, 162.1080103 , 175.09314147,
       167.46710095, 169.63486858, 169.6304048 , 172.79781109,
       166.73301951, 176.6759194 , 164.38870497, 182.32234104,
       161.74259878, 166.98466847, 176.29921877, 172.40414749,
       174.52217099, 169.48445103, 162.99610375, 165.5165349 ,
       171.30133222, 166.70309181, 174.77777247, 163.35135898,
       174.75513853, 164.70193616, 171.13312086, 170.52325218,
       174.50330356, 163.52846039, 163.63149866, 169.04599362,
       169.7732105 , 177.71520563, 161.33020887, 175.13241698,
       165.20494728, 166.09966494])

In [59]:
tall_women = (women_dist > men_dist).sum()
tall_women / 100


0.1

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 

    What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

    What is the probability that we observe an installation issue within the first 150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?



In [65]:
cor_file = (1/250)
stud_trials = 50
sim_it = 10000

In [69]:
break_sim = np.random.random((sim_it, stud_trials))

In [74]:
(break_sim < cor_file).sum() / len(break_sim)

0.1981

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?



8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

Be sure to add, commit, and push your work.

